name: Production
on:
  workflow_dispatch:

jobs:
  update_avatar_gist:
    uses: ./.github/workflows/update_avatar_gist.yml
    secrets: inherit
    
  update_stats_gist:
    uses: ./.github/workflows/update_stats_gist.yml
    secrets: inherit