name: Update Stats Gist
on:
  workflow_dispatch:
  schedule:
    - cron: '5 0-16/2 * * *'
  workflow_call:
    secrets:
      GH_PAT:
         required: true
      STATS_GIST_ID:
         required: true
      HABITICA_USER_ID:
         required: true
      HABITICA_API_KEY:
         required: true

jobs:
  update_stats_gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Check for cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          upload-chunk-size: 3000000
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Update stats
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          STATS_GIST_ID: ${{ secrets.STATS_GIST_ID }}
          HABITICA_USER_ID: ${{ secrets.HABITICA_USER_ID }}
          HABITICA_API_KEY: ${{ secrets.HABITICA_API_KEY }}
        run: bundle exec rake stat_box